const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Behaviors.Flash,
		C3.Behaviors.solid,
		C3.Plugins.TiledBg,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Behaviors.EightDir,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Behaviors.Anchor,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.EveryTick,
		C3.ScriptsInEvents.EventosFloresta_Event5_Act2,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.Wait,
		C3.ScriptsInEvents.EventosFloresta_Event12_Act3,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.ScriptsInEvents.EventosFloresta_Event15_Act3,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Count,
		C3.ScriptsInEvents.EventosFloresta_Event18_Act1,
		C3.ScriptsInEvents.EventosFloresta_Event21_Act1,
		C3.ScriptsInEvents.EventosFloresta_Event21_Act4,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.ScriptsInEvents.EventosTelaGolemAcorda_Event8_Act1,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.ScriptsInEvents.FolhaDeEventosDaFaseDoFimDoJogo_Event4_Act2,
		C3.ScriptsInEvents.FolhaDeEventosDaFase2_Event6_Act4,
		C3.ScriptsInEvents.FolhaDeEventosDaFase2_Event7_Act2,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.ScriptsInEvents.FolhaDeEventosGameOver_Event1_Act2,
		C3.ScriptsInEvents.FolhaDeEventosPb_Event1_Act2,
		C3.ScriptsInEvents.FolhaDeEventosJogabilidade_Event1_Act1,
		C3.ScriptsInEvents.EventosTelaInicial_Event1_Act2,
		C3.ScriptsInEvents.EventosTelaInicial_Event2_Act1
	];
};
self.C3_JsPropNameTable = [
	{CentrarEm: 0},
	{Plataforma: 0},
	{golem: 0},
	{Piscar: 0},
	{Sólido: 0},
	{inimigo: 0},
	{arvores: 0},
	{zonaDeAtivação: 0},
	{planoDeFundoArvores: 0},
	{Teclado: 0},
	{telaInicialPlano: 0},
	{Mouse: 0},
	{"8Direções": 0},
	{golemDeitado: 0},
	{ent: 0},
	{Toque: 0},
	{play: 0},
	{PlanoDeFundoEmBlocos: 0},
	{PlanoDeFundoEmBlocos3: 0},
	{Áudio: 0},
	{plataforma: 0},
	{Âncora: 0},
	{vida_HUD: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{pad: 0},
	{Senóide: 0},
	{slime: 0},
	{portal: 0},
	{golem2: 0},
	{PlanoDeFundoEmBlocos4: 0},
	{botãoGo: 0},
	{inimigo2: 0},
	{portal2: 0},
	{cristal: 0},
	{cristalsp: 0},
	{golem3: 0},
	{plataformaFimDoJogo: 0},
	{PlanoDeFundoEmBlocos5: 0},
	{Texto: 0},
	{escrita: 0},
	{colisãoTelaAcorda: 0},
	{cabeçaArvore: 0},
	{Texto2: 0},
	{jogabilidade: 0},
	{PlanoDeFundoEmBlocos6: 0},
	{botãoVoltarTelaInício: 0},
	{Texto3: 0},
	{vidas: 0}
];

self.InstanceType = {
	golem: class extends self.ISpriteInstance {},
	inimigo: class extends self.ISpriteInstance {},
	arvores: class extends self.ITiledBackgroundInstance {},
	zonaDeAtivação: class extends self.ISpriteInstance {},
	planoDeFundoArvores: class extends self.ITiledBackgroundInstance {},
	Teclado: class extends self.IInstance {},
	telaInicialPlano: class extends self.ITiledBackgroundInstance {},
	Mouse: class extends self.IInstance {},
	golemDeitado: class extends self.ISpriteInstance {},
	ent: class extends self.ISpriteInstance {},
	Toque: class extends self.IInstance {},
	play: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos3: class extends self.ITiledBackgroundInstance {},
	Áudio: class extends self.IInstance {},
	plataforma: class extends self.ISpriteInstance {},
	vida_HUD: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	pad: class extends self.ISpriteInstance {},
	slime: class extends self.ISpriteInstance {},
	portal: class extends self.ISpriteInstance {},
	golem2: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos4: class extends self.ITiledBackgroundInstance {},
	botãoGo: class extends self.ISpriteInstance {},
	inimigo2: class extends self.ISpriteInstance {},
	portal2: class extends self.ISpriteInstance {},
	cristal: class extends self.ISpriteInstance {},
	cristalsp: class extends self.ISpriteInstance {},
	golem3: class extends self.ISpriteInstance {},
	plataformaFimDoJogo: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos5: class extends self.ITiledBackgroundInstance {},
	Texto: class extends self.ITextInstance {},
	escrita: class extends self.ISpriteInstance {},
	colisãoTelaAcorda: class extends self.ISpriteInstance {},
	cabeçaArvore: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {},
	jogabilidade: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos6: class extends self.ITiledBackgroundInstance {},
	botãoVoltarTelaInício: class extends self.ISpriteInstance {},
	Texto3: class extends self.ITextInstance {}
}